/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import databases.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class superadmin extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form test
     */
    public superadmin() {
        initComponents();
        pHome.setVisible(true);
        pKategori.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pUser.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        
        datatableKategori();
        
        setLocationRelativeTo(null);
    }
    
    protected void datatableKategori(){
        Object[] Baris = {"Nomor", "Nama Kategori"};
        tabmode = new DefaultTableModel(null, Baris);
        jTablekategori.setModel(tabmode);
        String sql = "select * from kategori_Obat order by id_kategori asc";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String id = hasil.getString("id_kategori");
                String nama_kategori = hasil.getString("nama_kategori");
                
                String[] data = {id,nama_kategori};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            System.err.println("Error: "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pn_navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtest2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jtestKategori = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jtest3 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jtestKategori1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jtest4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jtestSuplayer2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jtestSuplayer4 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jtestSuplayer5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jtestSuplayer = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jtestSuplayer3 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jtestSuplayer6 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pKategori = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablekategori = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pUser = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pRfobat = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pObat = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pPenjualan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pPembelian = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setSize(new java.awt.Dimension(0, 0));

        pn_navbar.setBackground(new java.awt.Color(0, 0, 0));
        pn_navbar.setForeground(new java.awt.Color(204, 255, 255));
        pn_navbar.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apotek-removebg-preview.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-40.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 675, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_navbarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setMaximumSize(new java.awt.Dimension(1280, 800));
        pn_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Master Data");
        pn_sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, 139, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Dashboard");
        pn_sidebar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 139, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Data ");
        pn_sidebar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 139, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Laporan");
        pn_sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, 139, -1));

        jtest2.setBackground(new java.awt.Color(255, 255, 255));
        jtest2.setForeground(new java.awt.Color(204, 204, 204));
        jtest2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtest2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtest2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtest2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtest2MouseExited(evt);
            }
        });
        jtest2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jtest2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel34.setText("Home");
        jtest2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 30));

        jtestKategori.setBackground(new java.awt.Color(255, 255, 255));
        jtestKategori.setForeground(new java.awt.Color(204, 204, 204));
        jtestKategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestKategoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestKategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestKategoriMouseExited(evt);
            }
        });
        jtestKategori.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-categories-30.png"))); // NOI18N
        jtestKategori.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel30.setText("Kategori Obat");
        jtestKategori.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtestKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        jtest3.setBackground(new java.awt.Color(255, 255, 255));
        jtest3.setForeground(new java.awt.Color(204, 204, 204));
        jtest3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtest3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtest3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtest3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtest3MouseExited(evt);
            }
        });
        jtest3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-form-30.png"))); // NOI18N
        jtest3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel36.setText("RF Obat");
        jtest3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        jtestKategori1.setBackground(new java.awt.Color(255, 255, 255));
        jtestKategori1.setForeground(new java.awt.Color(204, 204, 204));
        jtestKategori1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestKategori1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestKategori1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestKategori1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestKategori1MouseExited(evt);
            }
        });
        jtestKategori1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-categories-30.png"))); // NOI18N
        jtestKategori1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel32.setText("Kategori Obat");
        jtestKategori1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtestKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        jtest4.setBackground(new java.awt.Color(255, 255, 255));
        jtest4.setForeground(new java.awt.Color(204, 204, 204));
        jtest4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtest4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtest4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtest4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtest4MouseExited(evt);
            }
        });
        jtest4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-form-30.png"))); // NOI18N
        jtest4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel38.setText("RF Obat");
        jtest4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtest4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        jtestSuplayer2.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer2.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayer2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayer2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayer2MouseExited(evt);
            }
        });
        jtestSuplayer2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-users-30.png"))); // NOI18N
        jtestSuplayer2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel40.setText("Data User");
        jtestSuplayer2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtestSuplayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, 30));

        jtestSuplayer4.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer4.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayer4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayer4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayer4MouseExited(evt);
            }
        });
        jtestSuplayer4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-30.png"))); // NOI18N
        jtestSuplayer4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel44.setText("Penjualan Obat");
        jtestSuplayer4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        jtestSuplayer5.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer5.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayer5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayer5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayer5MouseExited(evt);
            }
        });
        jtestSuplayer5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-30.png"))); // NOI18N
        jtestSuplayer5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel46.setText("Penjualan Obat");
        jtestSuplayer5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        jtestSuplayer4.add(jtestSuplayer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 30));

        pn_sidebar.add(jtestSuplayer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 30));

        jtestSuplayer.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayerMouseExited(evt);
            }
        });
        jtestSuplayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buy-30.png"))); // NOI18N
        jtestSuplayer.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel42.setText("Pembelian Obat");
        jtestSuplayer.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 30));

        jtestSuplayer3.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer3.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayer3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayer3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayer3MouseExited(evt);
            }
        });
        jtestSuplayer3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sell-30.png"))); // NOI18N
        jtestSuplayer3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel48.setText("Penjualan Obat");
        jtestSuplayer3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        jtestSuplayer.add(jtestSuplayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 30));

        pn_sidebar.add(jtestSuplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 30));

        jtestSuplayer6.setBackground(new java.awt.Color(255, 255, 255));
        jtestSuplayer6.setForeground(new java.awt.Color(204, 204, 204));
        jtestSuplayer6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtestSuplayer6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtestSuplayer6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtestSuplayer6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtestSuplayer6MouseExited(evt);
            }
        });
        jtestSuplayer6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-medicines-30.png"))); // NOI18N
        jtestSuplayer6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jLabel50.setText("Data Obat");
        jtestSuplayer6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 30));

        pn_sidebar.add(jtestSuplayer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 170, 30));

        pHome.setBackground(new java.awt.Color(255, 0, 102));
        pHome.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel14.setText("DASHBOARD SUPER ADMIN");

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(590, Short.MAX_VALUE))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        pKategori.setBackground(new java.awt.Color(204, 255, 204));
        pKategori.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel15.setText("KATEGORI");

        jTablekategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Nama Kategori"
            }
        ));
        jScrollPane1.setViewportView(jTablekategori);

        jButton1.setText("Cetak brok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKategoriLayout = new javax.swing.GroupLayout(pKategori);
        pKategori.setLayout(pKategoriLayout);
        pKategoriLayout.setHorizontalGroup(
            pKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKategoriLayout.createSequentialGroup()
                .addGroup(pKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKategoriLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15))
                    .addGroup(pKategoriLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        pKategoriLayout.setVerticalGroup(
            pKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKategoriLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel15)
                .addGroup(pKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKategoriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pKategoriLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        pUser.setBackground(new java.awt.Color(255, 255, 0));
        pUser.setMaximumSize(new java.awt.Dimension(1280, 800));
        pUser.setPreferredSize(new java.awt.Dimension(748, 531));

        jLabel17.setText("Form User");

        javax.swing.GroupLayout pUserLayout = new javax.swing.GroupLayout(pUser);
        pUser.setLayout(pUserLayout);
        pUserLayout.setHorizontalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addContainerGap(672, Short.MAX_VALUE))
        );
        pUserLayout.setVerticalGroup(
            pUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        pRfobat.setBackground(new java.awt.Color(51, 51, 255));
        pRfobat.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel16.setText("Request Form Obat");

        javax.swing.GroupLayout pRfobatLayout = new javax.swing.GroupLayout(pRfobat);
        pRfobat.setLayout(pRfobatLayout);
        pRfobatLayout.setHorizontalGroup(
            pRfobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRfobatLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(622, Short.MAX_VALUE))
        );
        pRfobatLayout.setVerticalGroup(
            pRfobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRfobatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        pObat.setBackground(new java.awt.Color(102, 0, 51));
        pObat.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel18.setText("Form Obat");

        javax.swing.GroupLayout pObatLayout = new javax.swing.GroupLayout(pObat);
        pObat.setLayout(pObatLayout);
        pObatLayout.setHorizontalGroup(
            pObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pObatLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addContainerGap(668, Short.MAX_VALUE))
        );
        pObatLayout.setVerticalGroup(
            pObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pObatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        pPenjualan.setBackground(new java.awt.Color(255, 0, 255));
        pPenjualan.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel19.setText("Form Penjualan Obat");

        javax.swing.GroupLayout pPenjualanLayout = new javax.swing.GroupLayout(pPenjualan);
        pPenjualan.setLayout(pPenjualanLayout);
        pPenjualanLayout.setHorizontalGroup(
            pPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenjualanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addContainerGap(616, Short.MAX_VALUE))
        );
        pPenjualanLayout.setVerticalGroup(
            pPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenjualanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        pPembelian.setBackground(new java.awt.Color(255, 204, 204));
        pPembelian.setMaximumSize(new java.awt.Dimension(1280, 800));

        jLabel20.setText("Form Pembelian Obat");

        javax.swing.GroupLayout pPembelianLayout = new javax.swing.GroupLayout(pPembelian);
        pPembelian.setLayout(pPembelianLayout);
        pPembelianLayout.setHorizontalGroup(
            pPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPembelianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        pPembelianLayout.setVerticalGroup(
            pPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPembelianLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 182, Short.MAX_VALUE)
                    .addComponent(pKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 182, Short.MAX_VALUE)
                    .addComponent(pRfobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 182, Short.MAX_VALUE)
                    .addComponent(pUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 182, Short.MAX_VALUE)
                    .addComponent(pObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 181, Short.MAX_VALUE)
                    .addComponent(pPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 180, Short.MAX_VALUE)
                    .addComponent(pPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(pKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(pRfobat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(pUser, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(pObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(pPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(pPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String reportPath = "src/view/testReport.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath,parameters, conn);
            JasperViewer viewer = new JasperViewer(print,false);
            viewer.setVisible(true);
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtest2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest2MouseClicked
        pHome.setVisible(true);
        pKategori.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtest2MouseClicked

    private void jtest2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest2MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtest2.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtest2MouseEntered

    private void jtest2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest2MouseExited
        jtest2.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtest2MouseExited

    private void jtestKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategoriMouseClicked
        pKategori.setVisible(true);
        pHome.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategoriMouseClicked

    private void jtestKategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategoriMouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestKategori.setBorder(border);        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategoriMouseEntered

    private void jtestKategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategoriMouseExited
        jtestKategori.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategoriMouseExited

    private void jtest3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest3MouseClicked
        pHome.setVisible(false);
        pKategori.setVisible(false);
        pRfobat.setVisible(true);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtest3MouseClicked

    private void jtest3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest3MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtest3.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtest3MouseEntered

    private void jtest3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest3MouseExited
        jtest3.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtest3MouseExited

    private void jtestKategori1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategori1MouseClicked
        pKategori.setVisible(true);
        pHome.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategori1MouseClicked

    private void jtestKategori1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategori1MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestKategori.setBorder(border);        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategori1MouseEntered

    private void jtestKategori1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestKategori1MouseExited
        jtestKategori.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jtestKategori1MouseExited

    private void jtest4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest4MouseClicked
        pHome.setVisible(false);
        pKategori.setVisible(false);
        pRfobat.setVisible(true);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtest4MouseClicked

    private void jtest4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest4MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtest3.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtest4MouseEntered

    private void jtest4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtest4MouseExited
        jtest3.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtest4MouseExited

    private void jtestSuplayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer2MouseClicked
        pKategori.setVisible(false);
        pHome.setVisible(false);
        pRfobat.setVisible(false);
        pUser.setVisible(true);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate(); 
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer2MouseClicked

    private void jtestSuplayer2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer2MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestSuplayer2.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer2MouseEntered

    private void jtestSuplayer2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer2MouseExited
        jtestSuplayer2.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer2MouseExited

    private void jtestSuplayer5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer5MouseClicked
        pHome.setVisible(false);
        pKategori.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(true);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer5MouseClicked

    private void jtestSuplayer5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer5MouseEntered

    private void jtestSuplayer5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer5MouseExited

    private void jtestSuplayer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer4MouseClicked
        pHome.setVisible(false);
        pKategori.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(true);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer4MouseClicked

    private void jtestSuplayer4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer4MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestSuplayer4.setBorder(border);        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer4MouseEntered

    private void jtestSuplayer4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer4MouseExited
        jtestSuplayer4.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer4MouseExited

    private void jtestSuplayer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer3MouseClicked
        pHome.setVisible(false);
        pKategori.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(true);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer3MouseClicked

    private void jtestSuplayer3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer3MouseEntered

    private void jtestSuplayer3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer3MouseExited

    private void jtestSuplayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayerMouseClicked
        pKategori.setVisible(false);
        pHome.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(false);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(true);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayerMouseClicked

    private void jtestSuplayerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayerMouseEntered

        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestSuplayer.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayerMouseEntered

    private void jtestSuplayerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayerMouseExited
        jtestSuplayer.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayerMouseExited

    private void jtestSuplayer6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer6MouseClicked
        pKategori.setVisible(false);
        pHome.setVisible(false);
        pRfobat.setVisible(false);
        pObat.setVisible(true);
        pPenjualan.setVisible(false);
        pPembelian.setVisible(false);
        pUser.setVisible(false);

        // Refresh tampilan setelah perubahan
        revalidate();
        repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer6MouseClicked

    private void jtestSuplayer6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer6MouseEntered
        Border border = BorderFactory.createLineBorder(new Color(102, 102, 102), 3); // Warna grey dengan ketebalan 3px
        jtestSuplayer6.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer6MouseEntered

    private void jtestSuplayer6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtestSuplayer6MouseExited
        jtestSuplayer6.setBorder(null);// TODO add your handling code here:
    }//GEN-LAST:event_jtestSuplayer6MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int option = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin keluar?", 
        "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablekategori;
    private javax.swing.JPanel jtest2;
    private javax.swing.JPanel jtest3;
    private javax.swing.JPanel jtest4;
    private javax.swing.JPanel jtestKategori;
    private javax.swing.JPanel jtestKategori1;
    private javax.swing.JPanel jtestSuplayer;
    private javax.swing.JPanel jtestSuplayer2;
    private javax.swing.JPanel jtestSuplayer3;
    private javax.swing.JPanel jtestSuplayer4;
    private javax.swing.JPanel jtestSuplayer5;
    private javax.swing.JPanel jtestSuplayer6;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pKategori;
    private javax.swing.JPanel pObat;
    private javax.swing.JPanel pPembelian;
    private javax.swing.JPanel pPenjualan;
    private javax.swing.JPanel pRfobat;
    private javax.swing.JPanel pUser;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    // End of variables declaration//GEN-END:variables
}
